name: "Feature CI"

on: 
  push:
   branches-ignore:
     - main

jobs: 
  ci-build:
    name: "CI Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: "Restore packages"
        run: dotnet restore
      - name: "Build"
        run: dotnet build --no-restore
      - name: "Test"
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true 


          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main